"""Edison banlist (March 2010 TCG) as data, plus an EDOPro lflist.

    python -m edison.build_banlist [--refresh]      # run edison.build_pool first

Source: edisonformat.net/rules/banlist, whose page script embeds the list as `ban`/`lim`/`sem`
arrays of card names. Names map to passcodes through edison/cardpool.csv.

Writes:
  banlist_2010_03.csv  id, name, copies, status - the 132 Forbidden/Limited/Semi-Limited cards
  edison.lflist.conf   EDOPro format. `$whitelist`: every card in the pool is listed (copies 3 unless
                       banned/limited), so EDOPro also rejects cards outside the Edison pool. Passcodes are
                       canonical (edison/aliases.csv), i.e. the ones the card database has. Drop it in
                       <EDOPro>/repositories/lflists/ or <EDOPro>/lflists/ to select it in the client.
"""
from __future__ import annotations

import argparse
import csv
from pathlib import Path

from edison import sources
from edison.aliases import canonical

HERE = Path(__file__).resolve().parent
TITLE = "Edison (2010.03 TCG)"
STATUS = {0: "Forbidden", 1: "Limited", 2: "Semi-Limited"}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--refresh", action="store_true")
    args = ap.parse_args()

    banlist = sources.edison_banlist(args.refresh)
    pool = list(csv.DictReader(open(HERE / "cardpool.csv")))
    ids = {r["name"]: r["id"] for r in pool}
    missing = sorted(n for n in banlist if n not in ids)
    if missing:
        raise SystemExit(f"banlist names not in cardpool.csv: {missing}")

    with open(HERE / "banlist_2010_03.csv", "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["id", "name", "copies", "status"])
        for name in sorted(banlist, key=lambda n: (banlist[n], n)):
            w.writerow([canonical(ids[name]), name, banlist[name], STATUS[banlist[name]]])

    no_id = []
    lines = [f"#[{TITLE}]", f"!{TITLE}", "$whitelist",
             "# Generated by edison/build_banlist.py from edisonformat.net (pool + March 2010 banlist)."]
    for copies, label in ((0, "forbidden"), (1, "limited"), (2, "semi-limited"), (3, "unlimited")):
        lines.append(f"#{label}")
        for r in sorted(pool, key=lambda r: r["name"]):
            if int(r["copies"]) != copies:
                continue
            if not r["id"]:
                no_id.append(r["name"])
                continue
            lines.append(f"{canonical(r['id'])} {copies} --{r['name']}")
    (HERE / "edison.lflist.conf").write_text("\n".join(lines) + "\n")

    counts = {STATUS[c]: sum(1 for v in banlist.values() if v == c) for c in STATUS}
    print(f"banlist {len(banlist)} {counts}")
    print(f"lflist entries {sum(1 for l in lines if l[:1].isdigit())}; pool cards without a passcode "
          f"(not in lflist): {no_id}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
